# Generated by Django 3.1.1 on 2022-12-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(help_text='emp_id', max_length=4, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
